### ISSUE TITLE
[Admin] Transfer bank account to the current board

### ISSUE THREAD

**Issue by i-am-sijia** [ZephyrTransport/management#34]
- Update (2/17/2023)
  - Lisa to email Rosella

**Comment by lmz** [comment]
We're going to transfer the current bank account to the current treasurer (me) and Vice Chair (Xuesong).  cc @rosellapicado

Steps:

- [ ] Remove Jonathan:
- [ ] Add Lisa:
- [ ] Add Xuesong:

**Comment by i-am-sijia** [comment]
The Vice Chair election happened during the [March 3rd Board meeting](https://docs.google.com/document/d/1-qgMQtD6k6U0kagsciTRNHXsdkdc9XEZexAsujS871s/edit).

**Comment by i-am-sijia** [comment]
I believe this has been completed by Lisa and Rosella when they met at TRB. @lmz anything else to add before we close this?

**Comment by lmz** [comment]
No - glad to finally close! :)
