### ISSUE TITLE
[Initiatives] Draft survey for Zephyr learning session topics

### ISSUE THREAD

**Issue by scottma89** [ZephyrTransport/management#36]
Draft for discussion here: https://docs.google.com/document/d/1BPEZFKq5KfnmkW-jCqtuNWx4uorZOGnZst3DOtR4_sw/edit#

**Comment by scottma89** [comment]
Some discussion items for today's board meeting:
- It may be a bit too detailed, we've tried to compensate by making many questions optional but might want to cut some questions
- We only ask for contact information if the respondent is open to moderating or presenting at a session. Is there anything we lose by not getting every respondent's name (we do ask everyone what type of role they're in)?
- We have a free response field if people want to suggest specific sessions but are there other ideas we want to include in the rate your interest question?

**Comment by AISTATHOPOULOS** [comment]
Hey everyone: I made the edits we discussed and we are getting close to a final version for the survey to send out: https://docs.google.com/document/d/1BPEZFKq5KfnmkW-jCqtuNWx4uorZOGnZst3DOtR4_sw/edit?usp=sharing

please add your last touches and ideas so we can launch!

**Comment by AISTATHOPOULOS** [comment]
I will likely only make the first 1/3 of our Friday meeting so let's try to get this in shape for approval by friday, cheers!

**Comment by AISTATHOPOULOS** [comment]
Thanks for finalizing!
