### ISSUE TITLE
Send out email for membership appeal in February 2024

### ISSUE THREAD

**Issue by i-am-sijia** [ZephyrTransport/management#41]
- [x] Draft email: Zephyr Communications > Communiqués > [2024 02 Membership Drive](https://docs.google.com/document/d/14qzNxRxiALpC_LioWMsf83YE4u5awI5L54i001RX9Nw/edit?usp=sharing)

**Comment by lmz** [comment]
The membership Google Sheet is current as of today (2/23/2024).

**Comment by i-am-sijia** [comment]
Membership email was sent on 4/9/2024.
