### ISSUE TITLE
Make Sijia and Simon the co-host of the board zoom meeting

### ISSUE THREAD

**Issue by i-am-sijia** [ZephyrTransport/management#42]
Currently no one can start the zoom meeting except Joe.

Background: When I sign in to the Zephyr zoom account, it asks for a verification code which is sent to admin@zephyrtranport.org. To sign in to the admin@zephyrtranport.org account, it uses 2FA and asks for a code sent to Joe's phone.

**Comment by scottma89** [comment]
Hi @i-am-sijia,

Adding co-hosts to the default meeting settings requires that the co-hosts be users on our zoom plan. We can add additional users at 14.99/month. There are a couple of alternative options we can try that wouldn't increase the cost.
1. Auto-forward the verification codes to the exec committee emails.
2. Switch the contact email for the zoom account to be a group list with exec.

For now, I have adjusted the meeting settings so participants can join at any time. We have screen sharing enabled for everyone in the meeting so the only things you wouldn't be able to do without the host account is edit polls and start/stop recording the meeting.

Let me know if you want me to set up one of the other options

**Comment by i-am-sijia** [comment]
Thank you @scottma89. Confirm that I can now start the meetings (both the board and the officers-only) as a participant.

However, screen share is still showing "Host disabled participant screen sharing". If you can please enable that, then the current solution should be enough. Thank you!

**Comment by i-am-sijia** [comment]
TODO - Sijia try to log in to the gmail account today.
